package com.sweetmeadow.api.bridge.domain.pojo;

public class ClientApp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_app.id
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_app.name
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_app.description
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_app.type
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_app.status
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_app.key
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    private String key;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_app.id
     *
     * @return the value of client_app.id
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_app.id
     *
     * @param id the value for client_app.id
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_app.name
     *
     * @return the value of client_app.name
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_app.name
     *
     * @param name the value for client_app.name
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_app.description
     *
     * @return the value of client_app.description
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_app.description
     *
     * @param description the value for client_app.description
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_app.type
     *
     * @return the value of client_app.type
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_app.type
     *
     * @param type the value for client_app.type
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_app.status
     *
     * @return the value of client_app.status
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_app.status
     *
     * @param status the value for client_app.status
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_app.key
     *
     * @return the value of client_app.key
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_app.key
     *
     * @param key the value for client_app.key
     *
     * @mbg.generated Sat Jun 17 16:58:23 CST 2017
     */
    public void setKey(String key) {
        this.key = key;
    }
}