package com.sweetmeadow.api.bridge.domain.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TRmPayflowExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public TRmPayflowExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andComNoIsNull() {
            addCriterion("com_no is null");
            return (Criteria) this;
        }

        public Criteria andComNoIsNotNull() {
            addCriterion("com_no is not null");
            return (Criteria) this;
        }

        public Criteria andComNoEqualTo(Long value) {
            addCriterion("com_no =", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoNotEqualTo(Long value) {
            addCriterion("com_no <>", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoGreaterThan(Long value) {
            addCriterion("com_no >", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoGreaterThanOrEqualTo(Long value) {
            addCriterion("com_no >=", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoLessThan(Long value) {
            addCriterion("com_no <", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoLessThanOrEqualTo(Long value) {
            addCriterion("com_no <=", value, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoIn(List<Long> values) {
            addCriterion("com_no in", values, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoNotIn(List<Long> values) {
            addCriterion("com_no not in", values, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoBetween(Long value1, Long value2) {
            addCriterion("com_no between", value1, value2, "comNo");
            return (Criteria) this;
        }

        public Criteria andComNoNotBetween(Long value1, Long value2) {
            addCriterion("com_no not between", value1, value2, "comNo");
            return (Criteria) this;
        }

        public Criteria andFlowIdIsNull() {
            addCriterion("flow_id is null");
            return (Criteria) this;
        }

        public Criteria andFlowIdIsNotNull() {
            addCriterion("flow_id is not null");
            return (Criteria) this;
        }

        public Criteria andFlowIdEqualTo(Short value) {
            addCriterion("flow_id =", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdNotEqualTo(Short value) {
            addCriterion("flow_id <>", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdGreaterThan(Short value) {
            addCriterion("flow_id >", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdGreaterThanOrEqualTo(Short value) {
            addCriterion("flow_id >=", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdLessThan(Short value) {
            addCriterion("flow_id <", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdLessThanOrEqualTo(Short value) {
            addCriterion("flow_id <=", value, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdIn(List<Short> values) {
            addCriterion("flow_id in", values, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdNotIn(List<Short> values) {
            addCriterion("flow_id not in", values, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdBetween(Short value1, Short value2) {
            addCriterion("flow_id between", value1, value2, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowIdNotBetween(Short value1, Short value2) {
            addCriterion("flow_id not between", value1, value2, "flowId");
            return (Criteria) this;
        }

        public Criteria andFlowNoIsNull() {
            addCriterion("flow_no is null");
            return (Criteria) this;
        }

        public Criteria andFlowNoIsNotNull() {
            addCriterion("flow_no is not null");
            return (Criteria) this;
        }

        public Criteria andFlowNoEqualTo(String value) {
            addCriterion("flow_no =", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotEqualTo(String value) {
            addCriterion("flow_no <>", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoGreaterThan(String value) {
            addCriterion("flow_no >", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoGreaterThanOrEqualTo(String value) {
            addCriterion("flow_no >=", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLessThan(String value) {
            addCriterion("flow_no <", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLessThanOrEqualTo(String value) {
            addCriterion("flow_no <=", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoLike(String value) {
            addCriterion("flow_no like", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotLike(String value) {
            addCriterion("flow_no not like", value, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoIn(List<String> values) {
            addCriterion("flow_no in", values, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotIn(List<String> values) {
            addCriterion("flow_no not in", values, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoBetween(String value1, String value2) {
            addCriterion("flow_no between", value1, value2, "flowNo");
            return (Criteria) this;
        }

        public Criteria andFlowNoNotBetween(String value1, String value2) {
            addCriterion("flow_no not between", value1, value2, "flowNo");
            return (Criteria) this;
        }

        public Criteria andSaleAmountIsNull() {
            addCriterion("sale_amount is null");
            return (Criteria) this;
        }

        public Criteria andSaleAmountIsNotNull() {
            addCriterion("sale_amount is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAmountEqualTo(BigDecimal value) {
            addCriterion("sale_amount =", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountNotEqualTo(BigDecimal value) {
            addCriterion("sale_amount <>", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountGreaterThan(BigDecimal value) {
            addCriterion("sale_amount >", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sale_amount >=", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountLessThan(BigDecimal value) {
            addCriterion("sale_amount <", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sale_amount <=", value, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountIn(List<BigDecimal> values) {
            addCriterion("sale_amount in", values, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountNotIn(List<BigDecimal> values) {
            addCriterion("sale_amount not in", values, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sale_amount between", value1, value2, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andSaleAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sale_amount not between", value1, value2, "saleAmount");
            return (Criteria) this;
        }

        public Criteria andBranchNoIsNull() {
            addCriterion("branch_no is null");
            return (Criteria) this;
        }

        public Criteria andBranchNoIsNotNull() {
            addCriterion("branch_no is not null");
            return (Criteria) this;
        }

        public Criteria andBranchNoEqualTo(String value) {
            addCriterion("branch_no =", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoNotEqualTo(String value) {
            addCriterion("branch_no <>", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoGreaterThan(String value) {
            addCriterion("branch_no >", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoGreaterThanOrEqualTo(String value) {
            addCriterion("branch_no >=", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoLessThan(String value) {
            addCriterion("branch_no <", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoLessThanOrEqualTo(String value) {
            addCriterion("branch_no <=", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoLike(String value) {
            addCriterion("branch_no like", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoNotLike(String value) {
            addCriterion("branch_no not like", value, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoIn(List<String> values) {
            addCriterion("branch_no in", values, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoNotIn(List<String> values) {
            addCriterion("branch_no not in", values, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoBetween(String value1, String value2) {
            addCriterion("branch_no between", value1, value2, "branchNo");
            return (Criteria) this;
        }

        public Criteria andBranchNoNotBetween(String value1, String value2) {
            addCriterion("branch_no not between", value1, value2, "branchNo");
            return (Criteria) this;
        }

        public Criteria andPayWayIsNull() {
            addCriterion("pay_way is null");
            return (Criteria) this;
        }

        public Criteria andPayWayIsNotNull() {
            addCriterion("pay_way is not null");
            return (Criteria) this;
        }

        public Criteria andPayWayEqualTo(String value) {
            addCriterion("pay_way =", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotEqualTo(String value) {
            addCriterion("pay_way <>", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayGreaterThan(String value) {
            addCriterion("pay_way >", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayGreaterThanOrEqualTo(String value) {
            addCriterion("pay_way >=", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLessThan(String value) {
            addCriterion("pay_way <", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLessThanOrEqualTo(String value) {
            addCriterion("pay_way <=", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayLike(String value) {
            addCriterion("pay_way like", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotLike(String value) {
            addCriterion("pay_way not like", value, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayIn(List<String> values) {
            addCriterion("pay_way in", values, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotIn(List<String> values) {
            addCriterion("pay_way not in", values, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayBetween(String value1, String value2) {
            addCriterion("pay_way between", value1, value2, "payWay");
            return (Criteria) this;
        }

        public Criteria andPayWayNotBetween(String value1, String value2) {
            addCriterion("pay_way not between", value1, value2, "payWay");
            return (Criteria) this;
        }

        public Criteria andSellWayIsNull() {
            addCriterion("sell_way is null");
            return (Criteria) this;
        }

        public Criteria andSellWayIsNotNull() {
            addCriterion("sell_way is not null");
            return (Criteria) this;
        }

        public Criteria andSellWayEqualTo(String value) {
            addCriterion("sell_way =", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayNotEqualTo(String value) {
            addCriterion("sell_way <>", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayGreaterThan(String value) {
            addCriterion("sell_way >", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayGreaterThanOrEqualTo(String value) {
            addCriterion("sell_way >=", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayLessThan(String value) {
            addCriterion("sell_way <", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayLessThanOrEqualTo(String value) {
            addCriterion("sell_way <=", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayLike(String value) {
            addCriterion("sell_way like", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayNotLike(String value) {
            addCriterion("sell_way not like", value, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayIn(List<String> values) {
            addCriterion("sell_way in", values, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayNotIn(List<String> values) {
            addCriterion("sell_way not in", values, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayBetween(String value1, String value2) {
            addCriterion("sell_way between", value1, value2, "sellWay");
            return (Criteria) this;
        }

        public Criteria andSellWayNotBetween(String value1, String value2) {
            addCriterion("sell_way not between", value1, value2, "sellWay");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNull() {
            addCriterion("card_no is null");
            return (Criteria) this;
        }

        public Criteria andCardNoIsNotNull() {
            addCriterion("card_no is not null");
            return (Criteria) this;
        }

        public Criteria andCardNoEqualTo(String value) {
            addCriterion("card_no =", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotEqualTo(String value) {
            addCriterion("card_no <>", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThan(String value) {
            addCriterion("card_no >", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoGreaterThanOrEqualTo(String value) {
            addCriterion("card_no >=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThan(String value) {
            addCriterion("card_no <", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLessThanOrEqualTo(String value) {
            addCriterion("card_no <=", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoLike(String value) {
            addCriterion("card_no like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotLike(String value) {
            addCriterion("card_no not like", value, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoIn(List<String> values) {
            addCriterion("card_no in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotIn(List<String> values) {
            addCriterion("card_no not in", values, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoBetween(String value1, String value2) {
            addCriterion("card_no between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andCardNoNotBetween(String value1, String value2) {
            addCriterion("card_no not between", value1, value2, "cardNo");
            return (Criteria) this;
        }

        public Criteria andVipNoIsNull() {
            addCriterion("vip_no is null");
            return (Criteria) this;
        }

        public Criteria andVipNoIsNotNull() {
            addCriterion("vip_no is not null");
            return (Criteria) this;
        }

        public Criteria andVipNoEqualTo(String value) {
            addCriterion("vip_no =", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoNotEqualTo(String value) {
            addCriterion("vip_no <>", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoGreaterThan(String value) {
            addCriterion("vip_no >", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoGreaterThanOrEqualTo(String value) {
            addCriterion("vip_no >=", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoLessThan(String value) {
            addCriterion("vip_no <", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoLessThanOrEqualTo(String value) {
            addCriterion("vip_no <=", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoLike(String value) {
            addCriterion("vip_no like", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoNotLike(String value) {
            addCriterion("vip_no not like", value, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoIn(List<String> values) {
            addCriterion("vip_no in", values, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoNotIn(List<String> values) {
            addCriterion("vip_no not in", values, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoBetween(String value1, String value2) {
            addCriterion("vip_no between", value1, value2, "vipNo");
            return (Criteria) this;
        }

        public Criteria andVipNoNotBetween(String value1, String value2) {
            addCriterion("vip_no not between", value1, value2, "vipNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoIsNull() {
            addCriterion("coin_no is null");
            return (Criteria) this;
        }

        public Criteria andCoinNoIsNotNull() {
            addCriterion("coin_no is not null");
            return (Criteria) this;
        }

        public Criteria andCoinNoEqualTo(String value) {
            addCriterion("coin_no =", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoNotEqualTo(String value) {
            addCriterion("coin_no <>", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoGreaterThan(String value) {
            addCriterion("coin_no >", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoGreaterThanOrEqualTo(String value) {
            addCriterion("coin_no >=", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoLessThan(String value) {
            addCriterion("coin_no <", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoLessThanOrEqualTo(String value) {
            addCriterion("coin_no <=", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoLike(String value) {
            addCriterion("coin_no like", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoNotLike(String value) {
            addCriterion("coin_no not like", value, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoIn(List<String> values) {
            addCriterion("coin_no in", values, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoNotIn(List<String> values) {
            addCriterion("coin_no not in", values, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoBetween(String value1, String value2) {
            addCriterion("coin_no between", value1, value2, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinNoNotBetween(String value1, String value2) {
            addCriterion("coin_no not between", value1, value2, "coinNo");
            return (Criteria) this;
        }

        public Criteria andCoinRateIsNull() {
            addCriterion("coin_rate is null");
            return (Criteria) this;
        }

        public Criteria andCoinRateIsNotNull() {
            addCriterion("coin_rate is not null");
            return (Criteria) this;
        }

        public Criteria andCoinRateEqualTo(BigDecimal value) {
            addCriterion("coin_rate =", value, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateNotEqualTo(BigDecimal value) {
            addCriterion("coin_rate <>", value, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateGreaterThan(BigDecimal value) {
            addCriterion("coin_rate >", value, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("coin_rate >=", value, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateLessThan(BigDecimal value) {
            addCriterion("coin_rate <", value, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("coin_rate <=", value, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateIn(List<BigDecimal> values) {
            addCriterion("coin_rate in", values, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateNotIn(List<BigDecimal> values) {
            addCriterion("coin_rate not in", values, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coin_rate between", value1, value2, "coinRate");
            return (Criteria) this;
        }

        public Criteria andCoinRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coin_rate not between", value1, value2, "coinRate");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNull() {
            addCriterion("pay_amount is null");
            return (Criteria) this;
        }

        public Criteria andPayAmountIsNotNull() {
            addCriterion("pay_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPayAmountEqualTo(BigDecimal value) {
            addCriterion("pay_amount =", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotEqualTo(BigDecimal value) {
            addCriterion("pay_amount <>", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThan(BigDecimal value) {
            addCriterion("pay_amount >", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_amount >=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThan(BigDecimal value) {
            addCriterion("pay_amount <", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pay_amount <=", value, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountIn(List<BigDecimal> values) {
            addCriterion("pay_amount in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotIn(List<BigDecimal> values) {
            addCriterion("pay_amount not in", values, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_amount between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pay_amount not between", value1, value2, "payAmount");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNull() {
            addCriterion("oper_date is null");
            return (Criteria) this;
        }

        public Criteria andOperDateIsNotNull() {
            addCriterion("oper_date is not null");
            return (Criteria) this;
        }

        public Criteria andOperDateEqualTo(Date value) {
            addCriterion("oper_date =", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotEqualTo(Date value) {
            addCriterion("oper_date <>", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThan(Date value) {
            addCriterion("oper_date >", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateGreaterThanOrEqualTo(Date value) {
            addCriterion("oper_date >=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThan(Date value) {
            addCriterion("oper_date <", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateLessThanOrEqualTo(Date value) {
            addCriterion("oper_date <=", value, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateIn(List<Date> values) {
            addCriterion("oper_date in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotIn(List<Date> values) {
            addCriterion("oper_date not in", values, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateBetween(Date value1, Date value2) {
            addCriterion("oper_date between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperDateNotBetween(Date value1, Date value2) {
            addCriterion("oper_date not between", value1, value2, "operDate");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNull() {
            addCriterion("oper_id is null");
            return (Criteria) this;
        }

        public Criteria andOperIdIsNotNull() {
            addCriterion("oper_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperIdEqualTo(String value) {
            addCriterion("oper_id =", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotEqualTo(String value) {
            addCriterion("oper_id <>", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThan(String value) {
            addCriterion("oper_id >", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("oper_id >=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThan(String value) {
            addCriterion("oper_id <", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLessThanOrEqualTo(String value) {
            addCriterion("oper_id <=", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdLike(String value) {
            addCriterion("oper_id like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotLike(String value) {
            addCriterion("oper_id not like", value, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdIn(List<String> values) {
            addCriterion("oper_id in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotIn(List<String> values) {
            addCriterion("oper_id not in", values, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdBetween(String value1, String value2) {
            addCriterion("oper_id between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andOperIdNotBetween(String value1, String value2) {
            addCriterion("oper_id not between", value1, value2, "operId");
            return (Criteria) this;
        }

        public Criteria andCounterNoIsNull() {
            addCriterion("counter_no is null");
            return (Criteria) this;
        }

        public Criteria andCounterNoIsNotNull() {
            addCriterion("counter_no is not null");
            return (Criteria) this;
        }

        public Criteria andCounterNoEqualTo(String value) {
            addCriterion("counter_no =", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoNotEqualTo(String value) {
            addCriterion("counter_no <>", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoGreaterThan(String value) {
            addCriterion("counter_no >", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoGreaterThanOrEqualTo(String value) {
            addCriterion("counter_no >=", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoLessThan(String value) {
            addCriterion("counter_no <", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoLessThanOrEqualTo(String value) {
            addCriterion("counter_no <=", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoLike(String value) {
            addCriterion("counter_no like", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoNotLike(String value) {
            addCriterion("counter_no not like", value, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoIn(List<String> values) {
            addCriterion("counter_no in", values, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoNotIn(List<String> values) {
            addCriterion("counter_no not in", values, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoBetween(String value1, String value2) {
            addCriterion("counter_no between", value1, value2, "counterNo");
            return (Criteria) this;
        }

        public Criteria andCounterNoNotBetween(String value1, String value2) {
            addCriterion("counter_no not between", value1, value2, "counterNo");
            return (Criteria) this;
        }

        public Criteria andSaleManIsNull() {
            addCriterion("sale_man is null");
            return (Criteria) this;
        }

        public Criteria andSaleManIsNotNull() {
            addCriterion("sale_man is not null");
            return (Criteria) this;
        }

        public Criteria andSaleManEqualTo(String value) {
            addCriterion("sale_man =", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManNotEqualTo(String value) {
            addCriterion("sale_man <>", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManGreaterThan(String value) {
            addCriterion("sale_man >", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManGreaterThanOrEqualTo(String value) {
            addCriterion("sale_man >=", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManLessThan(String value) {
            addCriterion("sale_man <", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManLessThanOrEqualTo(String value) {
            addCriterion("sale_man <=", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManLike(String value) {
            addCriterion("sale_man like", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManNotLike(String value) {
            addCriterion("sale_man not like", value, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManIn(List<String> values) {
            addCriterion("sale_man in", values, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManNotIn(List<String> values) {
            addCriterion("sale_man not in", values, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManBetween(String value1, String value2) {
            addCriterion("sale_man between", value1, value2, "saleMan");
            return (Criteria) this;
        }

        public Criteria andSaleManNotBetween(String value1, String value2) {
            addCriterion("sale_man not between", value1, value2, "saleMan");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoIsNull() {
            addCriterion("voucher_no is null");
            return (Criteria) this;
        }

        public Criteria andVoucherNoIsNotNull() {
            addCriterion("voucher_no is not null");
            return (Criteria) this;
        }

        public Criteria andVoucherNoEqualTo(String value) {
            addCriterion("voucher_no =", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoNotEqualTo(String value) {
            addCriterion("voucher_no <>", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoGreaterThan(String value) {
            addCriterion("voucher_no >", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoGreaterThanOrEqualTo(String value) {
            addCriterion("voucher_no >=", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoLessThan(String value) {
            addCriterion("voucher_no <", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoLessThanOrEqualTo(String value) {
            addCriterion("voucher_no <=", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoLike(String value) {
            addCriterion("voucher_no like", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoNotLike(String value) {
            addCriterion("voucher_no not like", value, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoIn(List<String> values) {
            addCriterion("voucher_no in", values, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoNotIn(List<String> values) {
            addCriterion("voucher_no not in", values, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoBetween(String value1, String value2) {
            addCriterion("voucher_no between", value1, value2, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andVoucherNoNotBetween(String value1, String value2) {
            addCriterion("voucher_no not between", value1, value2, "voucherNo");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagIsNull() {
            addCriterion("remote_flag is null");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagIsNotNull() {
            addCriterion("remote_flag is not null");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagEqualTo(String value) {
            addCriterion("remote_flag =", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagNotEqualTo(String value) {
            addCriterion("remote_flag <>", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagGreaterThan(String value) {
            addCriterion("remote_flag >", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagGreaterThanOrEqualTo(String value) {
            addCriterion("remote_flag >=", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagLessThan(String value) {
            addCriterion("remote_flag <", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagLessThanOrEqualTo(String value) {
            addCriterion("remote_flag <=", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagLike(String value) {
            addCriterion("remote_flag like", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagNotLike(String value) {
            addCriterion("remote_flag not like", value, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagIn(List<String> values) {
            addCriterion("remote_flag in", values, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagNotIn(List<String> values) {
            addCriterion("remote_flag not in", values, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagBetween(String value1, String value2) {
            addCriterion("remote_flag between", value1, value2, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andRemoteFlagNotBetween(String value1, String value2) {
            addCriterion("remote_flag not between", value1, value2, "remoteFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagIsNull() {
            addCriterion("exchange_flag is null");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagIsNotNull() {
            addCriterion("exchange_flag is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagEqualTo(String value) {
            addCriterion("exchange_flag =", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagNotEqualTo(String value) {
            addCriterion("exchange_flag <>", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagGreaterThan(String value) {
            addCriterion("exchange_flag >", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagGreaterThanOrEqualTo(String value) {
            addCriterion("exchange_flag >=", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagLessThan(String value) {
            addCriterion("exchange_flag <", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagLessThanOrEqualTo(String value) {
            addCriterion("exchange_flag <=", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagLike(String value) {
            addCriterion("exchange_flag like", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagNotLike(String value) {
            addCriterion("exchange_flag not like", value, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagIn(List<String> values) {
            addCriterion("exchange_flag in", values, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagNotIn(List<String> values) {
            addCriterion("exchange_flag not in", values, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagBetween(String value1, String value2) {
            addCriterion("exchange_flag between", value1, value2, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andExchangeFlagNotBetween(String value1, String value2) {
            addCriterion("exchange_flag not between", value1, value2, "exchangeFlag");
            return (Criteria) this;
        }

        public Criteria andShiftNoIsNull() {
            addCriterion("shift_no is null");
            return (Criteria) this;
        }

        public Criteria andShiftNoIsNotNull() {
            addCriterion("shift_no is not null");
            return (Criteria) this;
        }

        public Criteria andShiftNoEqualTo(String value) {
            addCriterion("shift_no =", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotEqualTo(String value) {
            addCriterion("shift_no <>", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoGreaterThan(String value) {
            addCriterion("shift_no >", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoGreaterThanOrEqualTo(String value) {
            addCriterion("shift_no >=", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoLessThan(String value) {
            addCriterion("shift_no <", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoLessThanOrEqualTo(String value) {
            addCriterion("shift_no <=", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoLike(String value) {
            addCriterion("shift_no like", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotLike(String value) {
            addCriterion("shift_no not like", value, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoIn(List<String> values) {
            addCriterion("shift_no in", values, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotIn(List<String> values) {
            addCriterion("shift_no not in", values, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoBetween(String value1, String value2) {
            addCriterion("shift_no between", value1, value2, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andShiftNoNotBetween(String value1, String value2) {
            addCriterion("shift_no not between", value1, value2, "shiftNo");
            return (Criteria) this;
        }

        public Criteria andComFlagIsNull() {
            addCriterion("com_flag is null");
            return (Criteria) this;
        }

        public Criteria andComFlagIsNotNull() {
            addCriterion("com_flag is not null");
            return (Criteria) this;
        }

        public Criteria andComFlagEqualTo(String value) {
            addCriterion("com_flag =", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagNotEqualTo(String value) {
            addCriterion("com_flag <>", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagGreaterThan(String value) {
            addCriterion("com_flag >", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagGreaterThanOrEqualTo(String value) {
            addCriterion("com_flag >=", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagLessThan(String value) {
            addCriterion("com_flag <", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagLessThanOrEqualTo(String value) {
            addCriterion("com_flag <=", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagLike(String value) {
            addCriterion("com_flag like", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagNotLike(String value) {
            addCriterion("com_flag not like", value, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagIn(List<String> values) {
            addCriterion("com_flag in", values, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagNotIn(List<String> values) {
            addCriterion("com_flag not in", values, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagBetween(String value1, String value2) {
            addCriterion("com_flag between", value1, value2, "comFlag");
            return (Criteria) this;
        }

        public Criteria andComFlagNotBetween(String value1, String value2) {
            addCriterion("com_flag not between", value1, value2, "comFlag");
            return (Criteria) this;
        }

        public Criteria andPosidIsNull() {
            addCriterion("posid is null");
            return (Criteria) this;
        }

        public Criteria andPosidIsNotNull() {
            addCriterion("posid is not null");
            return (Criteria) this;
        }

        public Criteria andPosidEqualTo(String value) {
            addCriterion("posid =", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotEqualTo(String value) {
            addCriterion("posid <>", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidGreaterThan(String value) {
            addCriterion("posid >", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidGreaterThanOrEqualTo(String value) {
            addCriterion("posid >=", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidLessThan(String value) {
            addCriterion("posid <", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidLessThanOrEqualTo(String value) {
            addCriterion("posid <=", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidLike(String value) {
            addCriterion("posid like", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotLike(String value) {
            addCriterion("posid not like", value, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidIn(List<String> values) {
            addCriterion("posid in", values, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotIn(List<String> values) {
            addCriterion("posid not in", values, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidBetween(String value1, String value2) {
            addCriterion("posid between", value1, value2, "posid");
            return (Criteria) this;
        }

        public Criteria andPosidNotBetween(String value1, String value2) {
            addCriterion("posid not between", value1, value2, "posid");
            return (Criteria) this;
        }

        public Criteria andUptimeIsNull() {
            addCriterion("uptime is null");
            return (Criteria) this;
        }

        public Criteria andUptimeIsNotNull() {
            addCriterion("uptime is not null");
            return (Criteria) this;
        }

        public Criteria andUptimeEqualTo(Date value) {
            addCriterion("uptime =", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotEqualTo(Date value) {
            addCriterion("uptime <>", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeGreaterThan(Date value) {
            addCriterion("uptime >", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("uptime >=", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeLessThan(Date value) {
            addCriterion("uptime <", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeLessThanOrEqualTo(Date value) {
            addCriterion("uptime <=", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeIn(List<Date> values) {
            addCriterion("uptime in", values, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotIn(List<Date> values) {
            addCriterion("uptime not in", values, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeBetween(Date value1, Date value2) {
            addCriterion("uptime between", value1, value2, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotBetween(Date value1, Date value2) {
            addCriterion("uptime not between", value1, value2, "uptime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 17 17:12:25 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.t_rm_payflow
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}