package com.sweetmeadow.api.bridge.domain.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TRmPayflow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.com_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private Long comNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.flow_id
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private Short flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.flow_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String flowNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.sale_amount
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private BigDecimal saleAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.branch_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String branchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.pay_way
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String payWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.sell_way
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String sellWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.card_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.vip_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String vipNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.coin_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String coinNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.coin_rate
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private BigDecimal coinRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.pay_amount
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.oper_date
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private Date operDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.oper_id
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String operId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.counter_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String counterNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.sale_man
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String saleMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.memo
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.voucher_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String voucherNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.remote_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String remoteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.exchange_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String exchangeFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.shift_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String shiftNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.com_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String comFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.posid
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private String posid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.t_rm_payflow.uptime
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    private Date uptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.com_no
     *
     * @return the value of dbo.t_rm_payflow.com_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public Long getComNo() {
        return comNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.com_no
     *
     * @param comNo the value for dbo.t_rm_payflow.com_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setComNo(Long comNo) {
        this.comNo = comNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.flow_id
     *
     * @return the value of dbo.t_rm_payflow.flow_id
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public Short getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.flow_id
     *
     * @param flowId the value for dbo.t_rm_payflow.flow_id
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setFlowId(Short flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.flow_no
     *
     * @return the value of dbo.t_rm_payflow.flow_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.flow_no
     *
     * @param flowNo the value for dbo.t_rm_payflow.flow_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.sale_amount
     *
     * @return the value of dbo.t_rm_payflow.sale_amount
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public BigDecimal getSaleAmount() {
        return saleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.sale_amount
     *
     * @param saleAmount the value for dbo.t_rm_payflow.sale_amount
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setSaleAmount(BigDecimal saleAmount) {
        this.saleAmount = saleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.branch_no
     *
     * @return the value of dbo.t_rm_payflow.branch_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getBranchNo() {
        return branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.branch_no
     *
     * @param branchNo the value for dbo.t_rm_payflow.branch_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setBranchNo(String branchNo) {
        this.branchNo = branchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.pay_way
     *
     * @return the value of dbo.t_rm_payflow.pay_way
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.pay_way
     *
     * @param payWay the value for dbo.t_rm_payflow.pay_way
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.sell_way
     *
     * @return the value of dbo.t_rm_payflow.sell_way
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getSellWay() {
        return sellWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.sell_way
     *
     * @param sellWay the value for dbo.t_rm_payflow.sell_way
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setSellWay(String sellWay) {
        this.sellWay = sellWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.card_no
     *
     * @return the value of dbo.t_rm_payflow.card_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.card_no
     *
     * @param cardNo the value for dbo.t_rm_payflow.card_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.vip_no
     *
     * @return the value of dbo.t_rm_payflow.vip_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getVipNo() {
        return vipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.vip_no
     *
     * @param vipNo the value for dbo.t_rm_payflow.vip_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setVipNo(String vipNo) {
        this.vipNo = vipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.coin_no
     *
     * @return the value of dbo.t_rm_payflow.coin_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getCoinNo() {
        return coinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.coin_no
     *
     * @param coinNo the value for dbo.t_rm_payflow.coin_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setCoinNo(String coinNo) {
        this.coinNo = coinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.coin_rate
     *
     * @return the value of dbo.t_rm_payflow.coin_rate
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public BigDecimal getCoinRate() {
        return coinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.coin_rate
     *
     * @param coinRate the value for dbo.t_rm_payflow.coin_rate
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setCoinRate(BigDecimal coinRate) {
        this.coinRate = coinRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.pay_amount
     *
     * @return the value of dbo.t_rm_payflow.pay_amount
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.pay_amount
     *
     * @param payAmount the value for dbo.t_rm_payflow.pay_amount
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.oper_date
     *
     * @return the value of dbo.t_rm_payflow.oper_date
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.oper_date
     *
     * @param operDate the value for dbo.t_rm_payflow.oper_date
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.oper_id
     *
     * @return the value of dbo.t_rm_payflow.oper_id
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getOperId() {
        return operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.oper_id
     *
     * @param operId the value for dbo.t_rm_payflow.oper_id
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setOperId(String operId) {
        this.operId = operId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.counter_no
     *
     * @return the value of dbo.t_rm_payflow.counter_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getCounterNo() {
        return counterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.counter_no
     *
     * @param counterNo the value for dbo.t_rm_payflow.counter_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setCounterNo(String counterNo) {
        this.counterNo = counterNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.sale_man
     *
     * @return the value of dbo.t_rm_payflow.sale_man
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getSaleMan() {
        return saleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.sale_man
     *
     * @param saleMan the value for dbo.t_rm_payflow.sale_man
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setSaleMan(String saleMan) {
        this.saleMan = saleMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.memo
     *
     * @return the value of dbo.t_rm_payflow.memo
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.memo
     *
     * @param memo the value for dbo.t_rm_payflow.memo
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.voucher_no
     *
     * @return the value of dbo.t_rm_payflow.voucher_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getVoucherNo() {
        return voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.voucher_no
     *
     * @param voucherNo the value for dbo.t_rm_payflow.voucher_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.remote_flag
     *
     * @return the value of dbo.t_rm_payflow.remote_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getRemoteFlag() {
        return remoteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.remote_flag
     *
     * @param remoteFlag the value for dbo.t_rm_payflow.remote_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setRemoteFlag(String remoteFlag) {
        this.remoteFlag = remoteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.exchange_flag
     *
     * @return the value of dbo.t_rm_payflow.exchange_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getExchangeFlag() {
        return exchangeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.exchange_flag
     *
     * @param exchangeFlag the value for dbo.t_rm_payflow.exchange_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setExchangeFlag(String exchangeFlag) {
        this.exchangeFlag = exchangeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.shift_no
     *
     * @return the value of dbo.t_rm_payflow.shift_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getShiftNo() {
        return shiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.shift_no
     *
     * @param shiftNo the value for dbo.t_rm_payflow.shift_no
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setShiftNo(String shiftNo) {
        this.shiftNo = shiftNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.com_flag
     *
     * @return the value of dbo.t_rm_payflow.com_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getComFlag() {
        return comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.com_flag
     *
     * @param comFlag the value for dbo.t_rm_payflow.com_flag
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setComFlag(String comFlag) {
        this.comFlag = comFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.posid
     *
     * @return the value of dbo.t_rm_payflow.posid
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public String getPosid() {
        return posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.posid
     *
     * @param posid the value for dbo.t_rm_payflow.posid
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setPosid(String posid) {
        this.posid = posid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.t_rm_payflow.uptime
     *
     * @return the value of dbo.t_rm_payflow.uptime
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.t_rm_payflow.uptime
     *
     * @param uptime the value for dbo.t_rm_payflow.uptime
     *
     * @mbg.generated Sat Jun 17 17:12:25 CST 2017
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }
}